version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careers_backend
    environment:
      - DATABASE_URL=sqlite:///./careers.db
      - JWT_SECRET=production-grade-super-secret-key-replace-in-real-deployment-min-32-chars
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - FRONTEND_URL=https://frontend-henna-ten-wg02ufviqk.vercel.app
      - APP_ENV=production
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: careers_frontend
    environment:
      - VITE_API_BASE_URL=https://careers-portal-x8lt.onrender.com
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_data:
